# Generated by Django 4.2.3 on 2023-07-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=3)),
                ('dates', models.JSONField()),
                ('rates', models.JSONField()),
            ],
        ),
    ]
