# Generated by Django 4.2.3 on 2023-07-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='coin',
            field=models.CharField(max_length=255),
        ),
    ]
