# Generated by Django 4.2.3 on 2023-07-22 22:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_currencyrate_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
